


import {React ,useEffect ,useState} from 'react'

const Useffectcounter = () => { 
   
       <>
       <div >
       <section>
       jbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnx
       </section>
       <section>
       jbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnx
       <img src='comp7.jpg' alt='asd'/>
       </section>
       
       <section>
       jbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnx
       </section>
       <section>
       jbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnx
       </section>
       
       <section>
       jbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnx
       </section>
       
       <section>
       jbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnxjbvfhbuhfbdjzcbvzjhdbvkzsjhfbvkzcjnx
       </section>
       
       </div>
       
       </> 

       
   

}

export default Useffectcounter
